@server = http://localhost:8000

### 전체 선수 조회
GET {{server}}/players

### 특정 선수 조회
GET {{server}}/players/1

### 선수 추가
POST {{server}}/players
Content-Type: application/json; charset=UTF-8

{
    "name": "손흥민",
    "age": 30,
    "team_id": 2
}

### 특정 선수 삭제
DELETE {{server}}/players/{{player_id}}

### 전체 팀 조회
GET {{server}}/teams

@team_id = 1

...

### 특정 팀 조회
GET {{server}}/teams//{{team_id}}